### ISSUE TITLE
Add templates and pre/post-processing creation scripts to the repository

### ISSUE THREAD

**Issue by metobom** [api3dao/api-integrations#228]
The scripts I used to create the pre/post-processing snippets in OIS files are not included in the repository. The scripts require templates to create pre/post-processing snippets so I will add the templates to the repository as well.

**Comment by metobom** [comment]
I expanded the scope of the issue by adding the below:
1. Added new files that include required information for pre/post-processing snippets in the OIS files
2. Added a script to creates one of the files I mentioned above for any API, this script will basically add a new data feed for any API by asking a series of questions to the user
3. Added a script to sync OIS files based on the files I mentioned in `1`

I won't be adding the templates, instead, I will be using the files mentioned in `1`.

## TODO
- [ ] Figure out why some API's pre/post-processing snippets are formed wrong
- [ ] Do test deployments
- [ ] Write a CI script to make sure the files mentioned in `1` and OIS files are synchronized
- [ ] Add the script mentioned in `3` to CI
